### ISSUE TITLE
Add syntax for smart_borders and smart_gaps

### ISSUE THREAD

**Issue by terminalnode** [terminalnode/sway-vim-syntax#5]
smart_borders \<on|no_gaps|off>
smart_gaps \<on|off>

**Comment by evan-chaney** [comment]
@terminalnode can this be closed now?

**Comment by terminalnode** [comment]
Yeah, sorry. I thought it would've closed automatically when "fixes #5" was mentioned in the request, like when mentioned it commits. But of course it doesn't because now that I think about it, that would be very strange.
